from low_shipping import find_lowest_shipping

find_lowest_shipping(2)
find_lowest_shipping(1.5)
find_lowest_shipping(4.8)
find_lowest_shipping(41.5)
find_lowest_shipping(8.07)
print()
find_lowest_shipping(0)
find_lowest_shipping([0])
find_lowest_shipping((0))
find_lowest_shipping((2))
find_lowest_shipping((1.5))
find_lowest_shipping((0, 2))
find_lowest_shipping(('zero'))
find_lowest_shipping('zero')
